### PR TITLE
Remove evoked response

### PR DESCRIPTION
**Pull request by joeyhsu**
Using brainstorm implementation of removing the average event-related potential from each trial:

https://neuroimage.usc.edu/brainstorm/Tutorials/Connectivity#:~:text=Remove%20evoked%20response%20from%20each,related%20potential%20from%20each%20trial.

### CODE REVIEW

**Comment by annesodub** [comment]
Hi Joey,

Thanks for create this new branch. 

1) I think the name of the column "Remove ERP" would be more meaningful with "Remove Avg". ERP stands for Evoked Related Potential and although is often used to refer to the average, there could be a confusion (e.g. a single trial is a response evoked by a stimulation hence a event related potential). What do you think? 

2) In create_table_workdir : I think that th code between line 111 and line 115 could be replaced by this one line.

remEvk = double(length(strfreq)==5 && isequal(strfreq{5},'removeEvoked')) ; 

Would you please test this? Thank you!

AnneSo

**Comment by joeyhsu** [comment]
Hi Anne-Sophie,

I will make those changes!

**Comment by annesodub** [comment]
Hi Joey, please let me know when your done so that I can merge! Thanks.

**Comment by joeyhsu** [comment]
Hi Anne-Sophie,

Just a question on #2: using double() makes the column values in the main GUI appears as "1.0" or "0.0". Perhaps instead could use an integer type (e.g. uint8()?) so that it just shows as "1" or "0"? Alternatively, could add a num2str() around double(). Or open to other ways of doing this! Thanks.

**Comment by annesodub** [comment]
Sure! num2str() around the double() works! thank you Joey.

**Pull request closed without merging**
