### PR TITLE
BST process to detect bad trials with SEEG data.

### PR DESCRIPTION
**Pull request by ws1011001**
Hi AnneSo,

Here is the bst process for trial rejection.
Please let me know if you have any questions.

Cheers,
Shuai

### CODE REVIEW

**Comment by annesodub** [comment]
Thank you Shuai. 

Just to give a bit more context to the PR, please let me paste the context we built together : 

The approach relies on 

1) Three criteria defined in ([Hirshorn et al., 2016](http://www.pnas.org/lookup/doi/10.1073/pnas.1604126113)).

      - Trials with peak amplitude **_N x SDs_** away from the mean across the rest of the trials
      - Absolute Peak amplitude larger than **_N μV_** (one value used per dataset) [OPTIONAL]
      - Absolute Gradient (between two consecutive time points) larger than **_N μV_**  (one value per input dataset) [OPTIONAL]
       
2)  One criteria defined in  ([Staresina et al., 2012](https://www.nature.com/articles/nn.3154)).

      - Relative peak and gradient thresholds :  **_Upper Fence_** /(three interquartile away from 75th percentile) / **_Inner Fence_**  are available as an alternative method (as opposed to absolute values for peak and gradient) to mark temporal outliers for each trial (values computed per trial) [OPTIONAL]

3) Finally we compute, by channel, the **_percentage of rejected trials_** (i.e. the percentage of trials rejected because of this channel). This allows this identification of potentially left bad channels (noisy, flat, showing epileptogenic activity)

The process GUI shows :

image

**Comment by annesodub** [comment]
I am looking for an open access iEEG dataset (e.g. [Speech Production in intracranial Electroencephalography: iBIDS dataset](https://osf.io/nrgx6/)) preprocessed/epoched and for which trial and channel rejection would have been performed (ground truth is known). This would allow us to asses this approach (see previous comment).

 @ftadel : do you know if such a dataset exists? Any other recommendations here?

**Comment by ftadel** [comment]
I am not aware on any public iEEG dataset beyond the ones that are released as BIDS-iEEG examples:
https://github.com/bids-standard/bids-examples

You could ask the authors of these datasets, they might have more information to share.

**Comment by annesodub** [comment]
Thank you Francois for your prompt answer! I will get in touch with the authors.

**Comment by annesodub** [comment]
@ws1011001 : I realize that you are working on the master branch. Would you please create a new branch for this commit? This would make it easier for me to review.

**Comment by ws1011001** [comment]
> @ws1011001 : I realize that you are working on the master branch. Would you please create a new branch for this commit? This would make it easier for me to review.
Yes, I created a new branch 'trial-rejection' in my forked repo but I don't what to do next?

**Comment by annesodub** [comment]
Would you please create a new pull request from this branch?

**Comment by ws1011001** [comment]
> @ws1011001 :would you please create a new pull request from this branch?

OK. I opened a pull request from my "trial-rejection" branch to your "dev" branch.

**Comment by ws1011001** [comment]
Hi,

This pull request will merge the codes into your master so I reopen it.

**Comment by annesodub** [comment]
Yes, but your branch name is still "master". Would you please : 
1) create a new branch (e.g. trial-rejection) 
2) PR a merge of this new branch on the **master** branch
3) let me know if you find any conflicts (there are 2 PR ahead), I can help solving them.

**Pull request closed without merging**
