### PR TITLE
Add remove evoked response functionality to time-frequency decomposition

### PR DESCRIPTION
**Pull request by joeyhsu**
Using brainstorm implementation of removing the average event-related potential from each trial:

https://neuroimage.usc.edu/brainstorm/Tutorials/Connectivity#:~:text=Remove%20evoked%20response%20from%20each,related%20potential%20from%20each%20trial.

### CODE REVIEW

**Comment by annesodub** [comment]
Hi Joey! Thank for the implementation of this option! Welcome on github! :-)

The main code do the job nicely. However I see a few modifications that should be implemented to make this feature  fully operational. This information about the removal (or not) has to be tracked for further processing. Additionally, the files produced with a set of parameters but no evoked response removal (freq bands, method, baseline montage, etc.) should not be overwritten by the ones with evoked responses. 

I think a way to implement this would be to process this information (evoked removed or not) in a similar way as we process the frequency step and add a tag "evk_rm" at the end of the field "Freq. band" (see column "Freq. band" from the table in the main GUI). This way, files produced with "Remove Evoked Response" ON will not overwrite the files produced with  "Remove Evoked Response" OFF.

What do you think? Please let me know if you need assistance.

**Comment by annesodub** [comment]
@joeyhsu : please let me know if you have any question

**Comment by joeyhsu** [comment]
Thanks Anne-Sophie, am working on it and will let you know.

**Comment by joeyhsu** [comment]
Hi Anne-Sophie,

In my original commit, I had added some code (line 81 of mia_s4_compute_tf_bandwise.m) that checks if the remove evoked option was checked, and if it was, to add a "removeEvoked" tag to the end of the filename (the "output" variable). I just tested this running without checking the remove evoked option and it appears currently it is able to output both types without overwriting? (see image below)

So perhaps the only "new" thing to add is a column in the main GUI (perhaps in between "Freq.band"and "'Nb stats" as you suggested) to track if the patient/file corresponds to processing with or without the removal of the evoked response.

Please let me know if this is what you were thinking.

Screen Shot 2021-09-20 at 10 35 53 AM

Screen Shot 2021-09-20 at 10 41 03 AM

**Comment by annesodub** [comment]
Hi Joey, 

Sorry I did not catch the modification in the mia_s4_compute_tf_bandwise which check for the existence of the file and add the tag. This looks good, thank you.
Yes, that make sense to add a column in the main table between Freq. band and stats. Do you think you can do that? 
Please let me know if I can help.

**Comment by joeyhsu** [comment]
Yes, I believe I was able to implement it! I think the new changes should be appearing with the pull request now?

**Pull request closed without merging**
